import type { Metadata } from "next";
import Link from "next/link";
import SubmissionsTable from "@/components/SubmissionsTable";

export const metadata: Metadata = {
  title: "Submissions Dashboard | AcdyOn",
  description: "Review all generated academic pathway recommendations.",
};

export default function SubmissionsPage() {
  return (
    <div className="min-h-screen bg-slate-100 py-10 px-4 sm:px-6 lg:px-8">
      <div className="mx-auto container-lg space-y-6">

        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-sm text-slate-500">
          <Link href="/" className="hover:text-sky-600 transition-colors">Home</Link>
          <span>/</span>
          <span className="text-slate-800 font-medium">Submissions</span>
        </nav>

        {/* Header */}
        <div className="rounded-2xl bg-white px-6 py-8 sm:px-10 card-shadow ring-1 ring-slate-200">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">
                Submissions Dashboard
              </h1>
              <p className="mt-2 text-slate-500 max-w-xl">
                All academic pathway recommendations generated by the engine.
              </p>
            </div>
            <Link
              href="/form"
              className="inline-flex items-center gap-2 rounded-full px-5 py-3 btn-primary text-sm font-semibold whitespace-nowrap self-start sm:self-auto"
            >
              New Recommendation →
            </Link>
          </div>
        </div>

        <SubmissionsTable />

      </div>
    </div>
  );
}
